config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'events#index'
  resources :users, only: [:show]
  #resources :events, only: [:new, :create]
  resources :events
  resources :users, only: [:show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :attendee, class_name: "User"
  belongs_to :event

  validates :stripe_customer_id,
    uniqueness: true




end

app/models/event.rb
class Event < ApplicationRecord
  has_many :attendances
  has_many :users, through: :attendances
  belongs_to :admin, class_name: "User"

  validates :start_date,
    presence: true
  validate :event_must_be_upcoming
  validates :duration,
    presence: true,
    numericality: { only_integer: true, greater_than: 0 }
  validate :duration_must_be_multiple_of_five
  validates :title,
    presence: true,
    length: { in: 5..140 }
  validates :description,
    presence: true,
    length: { in: 20..1000 }
  validates :price,
    presence: true,
    numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 1000 }
  validates :location,
    presence: true
  
  def event_must_be_upcoming
    if start_date.present?
      unless start_date > Time.now
        errors.add(:start_date, "must be upcoming")
      end
    end
  end
  
  def duration_must_be_multiple_of_five
    if duration.present?
      unless duration % 5 == 0
        errors.add(:duration, "must be multiple of 5")
      end
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :attendances, foreign_key: 'attendee_id', class_name: "Attendance"
  has_many :events, through: :attendances
  has_many :events, foreign_key: 'admin_id', class_name: "Event"



 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]

  def index
    @events = Event.all.order(:start_date)
  end

  def new
    @event=Event.new
  end

def create
  @event = Event.new(title: params[:title],description: params[:description],location: params[:location], start_date: params[:start_date],duration: params[:duration], price: params[:price], admin_id: current_user.id)
  
   if @event.save
    redirect_to(root_path, notice: "Event successfully created!")
   else
    render '/events/new.html.erb'
   
  end
  end

  def show
    @event = Event.find(params[:id])
   end

end

app/controllers/user_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!, only: [:show]
    
    def show
        @user = User.find_by(id: current_user.id)
        @event = Event.where(user_id: current_user.id)
      end
    
    def signedinuserprofile
      profile = User.find(current_user.id)
      if profile.nil?
        redirect_to "/profile/new"
      end
    end
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!, only: [:show]

  def show
    @user = User.find_by(id: current_user.id)
    @event = Event.where(user_id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<% if notice == "Event successfully created!" %>
<div class="alert alert-success" role="alert">
<p> Event successfully saved </p></div>

<% end %>


<div class="jumbotron" style="background-image: url(https://images.unsplash.com/photo-1495442358998-961b69f45703?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1650&q=80)">
  <h1 class="display-4">Find events you love in Paris</h1>
  <p class="lead">We offer exceptional events in Paris</p>
  <hr class="my-4">
  <p>Create and participate in concerts, tastings and other events.</p>
  <p class="lead">
    <%= link_to "Create an event", new_event_path, :class => "btn btn-primary btn-lg" %>
  </p>
</div>
<body>
    </div>
    <section class="container mt-4 mb-4">
        
        <div  class="card-deck mb-3 d-flex justify-content-between">
          <% @events.each.with_index(1) do |event, index| %>
            <div class="col-sm-4 mt-6 mb-4">
              <div class="card">
                <div class="card-body d-flex align-items-center flex-column">
                  <h5 class="card-title"><%= link_to "Event n°#{index}", events_path(event.id) %></h5>
                  <p class="card-text"><%= event.title %></p>
                  <p class="card-text"><%= event.start_date %></p>
                  <%= link_to "view the full event", event_path(event.id), :class =>"btn btn-primary" %>
                </div>
              </div>
            </div>
          <%end %>
        </div>
  </section>
</body>

app/views/events/new.html.erb
<br /> <br />

<% if @event.errors.any? %>
<div class="alert alert-danger" role="alert">
  <br>
  <p>❌&nbsp;&nbsp;Nous n'avons pas réussi à créer l'événement pour la (ou les) raison(s) suivante(s) :</p>
  <ul>
    <% @event.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<br>
</div>
<% end %>

 <center>
<%= form_tag events_path, method: "POST" do %>
    <div class="form-group mb-2">
      <%= text_field_tag :title, params[:title], class: 'form-control col-sm-3', placeholder: 'Title* (between 5 and 140 characters)' %>
    </div>
    <br>
    <div class="form-group mb-2">
      <%= text_field_tag :start_date, params[:start_date], class: 'form-control col-sm-5', placeholder: 'Start date* (format : YYYY-MM-DD)' %>
    </div>
    <br>
    <div class="form-group mb-2">
      <%= text_field_tag :duration, params[:duration], class: 'form-control col-sm-5', placeholder: 'Duration* (in minutes and triple of 5)' %>
    </div>
    <br>
    <div class="form-group mb-2">
      <%= text_field_tag :price, params[:price], class: 'form-control col-sm-3', placeholder: 'Price* (between 1 and 1000 €)' %>
    </div>
    <br>
     <div class="form-group mb-2">
      <%= text_field_tag :location, params[:location], class: 'form-control col-sm-3', placeholder: 'Location*' %>
    </div>
    <br>
    <div class="form-group">
      <%= text_area_tag :description, params[:description], class: 'form-control col-sm-7', placeholder: 'Description*' %>
    </div>
    <br>
      <%= submit_tag "Save new event", class: 'btn btn-primary' %>

  <% end %>
</div>

</center>

app/views/events/show.html.erb
<h4 class="h1 mt-3 mb-4 ml-3 text-center">Discover the event: <%= @event.title %></h4>
<container class="d-flex justify-content-around">
  <div class="card-deck mb-3 d-flex justify-content-between" style="width: 36rem;">
      <div class="card mx-4" style="width: 26rem;">
        <div class="card-body">
          <h5 class="card-title">Learn more about the event: '<%= @event.title %>'</h5>
          <h4 class="card-text mb-4"><small class="text-muted">Event description: <%= @event.description %></small></h4>
          <h4 class="card-text mb-4"><small class="text-muted">Location: <%= @event.location %></small></h4>
          <h4 class="card-text mb-4"><small class="text-muted">Duration in min: <%= @event.duration %></small></h4>
          <h4 class="card-text mb-4"><small class="text-muted">Price in € : <%=  @event.price %></small></h4>
          <h4 class="card-text mb-4"><small class="text-muted">Start date: <%=  @event.start_date %></small></h4>
          <h4 class="card-text mb-4"><small class="text-muted">End date: <%=@event.start_date + @event.duration*60%></small></h4>
          <h5>Event created by: <%= @event.admin.email %></h5>
          <center>
          <%= link_to "See all my created events", user_path(current_user), :class => "btn btn-primary" %>
          <%= link_to "Join event", user_path(current_user), :class => "btn btn-primary" %>

          </div>
      </div>
    </div>

    </container>
  <br>

  <p class="lead mt-3 mb-4 ml-3 text-center"><%= link_to "Return to the homepage", root_path, :class => "btn btn-primary" %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EventbriteDevise</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://stackpath.bootstrapcdn.com/bootswatch/4.4.1/flatly/bootstrap.min.css" rel="stylesheet" integrity="sha384-yrfSO0DBjS56u5M+SjWTyAHujrkiYVtRYh2dtB3yLQtUz3bodOeialO59u5lUCFF" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <body>
  <!-- Navbar-->
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <%= link_to "The Paris Events Platform", root_path, :class => "navbar-brand"%>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <%= link_to "Home", root_path, :class => "nav-link"%>
        </li>
        <li class="nav-item">
          <%= link_to "New event", new_event_path, :class => "nav-link"%>
        </li>
      </ul>

    <% if current_user == nil %>
    <%= link_to "Connect", new_user_session_path, :class => "btn btn-outline-primary" %>
    <%= link_to "Create account", new_user_registration_path, :class => "btn btn-outline-primary" %>

    <% else  %>
    <%= link_to "Profil", user_path(current_user), :class => "btn btn-outline-primary" %>
    <%= link_to "Log out", destroy_user_session_path, method: :delete, :class => "btn btn-outline-primary" %>
    <%= link_to "Settings", edit_user_registration_path, :class => "btn btn-outline-primary" %>
    <% end %>

    </div>
    </nav>
    <div id="zero">
  <%= yield %>




    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

app/views/users/show.html.erb
<br>
<br>
<center>
<h2>Welcome   :<%= mail_to current_user.email %> </h2> 

<div class="row">
<% @event.each do |e| %>
  <div class="col m3">
    <div class="card">
      <div class="card-image">
        <img src="https://i.picsum.photos/id/337/300/150.jpg">
      <div class="card-content">
        <p style="color: #ff7043;"><%= e.start %></p>
          <%= link_to e.title, event_path(e.id)%>
        <p><small><%= e.location%></small></p>
      </div>
    </div>
  </div>
</div>
<% end %>






   


  